#
# Phoenix-RTOS
#
# Raspberry Pi 4 (BCM2711) hardware RNG (iproc RNG200)
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
#

NAME := rpi4-hwrng
LOCAL_SRCS := rpi4-hwrng.c

include $(binary.mk)
