#
# Phoenix-RTOS
#
# Raspberry Pi 4 (BCM2711) boot system-info banner (rpi4-sysinfo)
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
#

NAME := rpi4-sysinfo
LOCAL_SRCS := rpi4-sysinfo.c

include $(binary.mk)
