#
# Phoenix-RTOS
#
# Raspberry Pi 4 (BCM2711) VideoCore framebuffer device (/dev/fb0)
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
#

NAME := rpi4-fb
LOCAL_SRCS := rpi4-fb.c

include $(binary.mk)
