#
# Phoenix-RTOS
#
# Raspberry Pi 4 (BCM2711) V3D GPU scout (Tier 3 diagnostic)
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
#

NAME := rpi4-v3d-scout
LOCAL_SRCS := rpi4-v3d-scout.c

include $(binary.mk)
