#
# Phoenix-RTOS
#
# Raspberry Pi 4 (BCM2711) SoC thermal / throttle sensor
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
#

NAME := rpi4-thermal
LOCAL_SRCS := rpi4-thermal.c

include $(binary.mk)
