#
# Phoenix-RTOS
#
# Raspberry Pi 4 kernel-log capture daemon (klogd) — task #31
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
#

NAME := rpi4-klogd
LOCAL_SRCS := rpi4-klogd.c

include $(binary.mk)
