#
# Makefile for Phoenix-RTOS PL011 tty driver
#
# Copyright 2026 Phoenix Systems
#
# %LICENSE%
#

NAME := pl011-tty
LOCAL_SRCS := pl011-tty.c teken/teken.c
DEP_LIBS := libtty libklog
include $(binary.mk)
