#
# Phoenix-RTOS
#
# Raspberry Pi 4 (BCM2711) AF_UNIX socket readiness probe (rpi4-ipcprobe)
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
#

NAME := rpi4-ipcprobe
LOCAL_SRCS := rpi4-ipcprobe.c

include $(binary.mk)
