#
# Phoenix-RTOS
#
# Raspberry Pi 4 (BCM2711) GPIO observer device (/dev/gpio)
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
#

NAME := rpi4-gpio
LOCAL_SRCS := rpi4-gpio.c

include $(binary.mk)
